/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Libro;

/**
 *
 * @author usuario
 */
public class PanelDatosLibro extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosLibro
     */
    public PanelDatosLibro() {
        initComponents();
    }
    
    public Libro getLibro(){
        Libro libro = new Libro(jtISBN.getText(), jtTitulo.getText(), jtAutor.getText());
        return libro;
    }
    
    public String getISBN(){
    return jtISBN.getText();
    }
  public boolean verificarDatos(){
      boolean variable=false;
      if(!jtAutor.getText().equalsIgnoreCase("")&
         !jtISBN.getText().equalsIgnoreCase("")&
         !jtTitulo.getText().equalsIgnoreCase("")){
          variable=true;
      }else{
          JOptionPane.showMessageDialog(null, "Digite todos los datos necesarios para agregar el libro", "ERROR", JOptionPane.ERROR_MESSAGE);
      }
      return variable;
  }
    public void borrarEspacios(){
        jtAutor.setText("");
        jtTitulo.setText("");
        jtISBN.setText("");
    }
    
    public void ErrorLibroExistente(){
        String mensaje="Este libro ya se encuentra registrado";
        JOptionPane.showMessageDialog(null,mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    public void libroExitosoAgregado(){
        String mensaje="El libro se agregó exitosamente";
         JOptionPane.showMessageDialog(null,mensaje);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlISBN = new javax.swing.JLabel();
        jtISBN = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jtAutor = new javax.swing.JTextField();

        setBackground(new java.awt.Color(36, 166, 166));

        jlISBN.setFont(new java.awt.Font("Droid Sans Fallback", 0, 18)); // NOI18N
        jlISBN.setText("ISBN");

        jlTitulo.setFont(new java.awt.Font("Droid Sans Fallback", 0, 18)); // NOI18N
        jlTitulo.setText("Título");

        jlAutor.setFont(new java.awt.Font("Droid Sans Fallback", 0, 18)); // NOI18N
        jlAutor.setText("Autor");

        jtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlISBN)
                        .addGap(18, 18, 18)
                        .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtAutor)
                            .addComponent(jtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN)
                    .addComponent(jtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtAutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtISBN;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables
}
